"""Render full-data shell/context characteristics next to existing NLL gaps."""
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

from describe_structure_features import OUT
from make_pair_feature_summary import label


def number(x,scale=1,decimals=3,signed=False):
    if not np.isfinite(x):
        return 'NA'
    return f'{scale*x:+.{decimals}f}' if signed else f'{scale*x:.{decimals}f}'


def render_section():
    data=pd.read_csv(OUT/'nll_comparison.csv')
    p1=data.loc[data.nll_study.eq('P1')]
    plt.rcParams.update({'font.family':'DejaVu Sans','font.size':9,'svg.hashsalt':'whole-data-shell-context'})
    fig,axes=plt.subplots(1,3,figsize=(15,5),layout='constrained')
    colors={2:'#277da8',3:'#a24a38',4:'#427b45',5:'#a16b13',6:'#784e9f',10:'#1d8280'}
    features=[('shell_excess_tv',1,'Shell TV minus nominal uniform-sampling reference'),
              ('context_display_sd',100,'Exact-display variation C (percentage points)'),
              ('swap_gap_effect',100,'One-item replacement: higher-h minus lower-h (pp)')]
    for ax,(metric,scale,title) in zip(axes,features):
        g=p1.loc[p1.delta.notna()&p1[metric].notna()]
        for r,group in g.groupby('r'):
            ax.scatter(scale*group[metric],group.delta,s=44,color=colors[int(r)],label=f'r = {int(r)}')
        for row in g.itertuples():
            if row.dataset in ['sushi_a','beans','wheat','patras_cost','dots2024_B_r6','00025-00000002']:
                ax.annotate(label(row.dataset),(scale*getattr(row,metric),row.delta),
                            xytext=(3,5),textcoords='offset points',fontsize=7)
        ax.axhline(0,color='#888',lw=.8);ax.axvline(0,color='#bbb',lw=.7)
        ax.set_title(f'{title}\n{len(g)} complete P1 comparisons',fontsize=9)
        ax.spines[['top','right']].set_visible(False)
        ax.grid(axis='y',alpha=.2);ax.margins(x=.3,y=.2)
        ax.legend(frameon=False,fontsize=7,ncols=3,loc='upper left')
    axes[0].set_ylabel('Recorded NLL(SM) - NLL(PL), nats/report')
    fig.suptitle('Characteristics 2 and 3: all reports, unchanged predictive comparisons',fontsize=13)
    fig.savefig(OUT/'feature_vs_nll.svg',metadata={'Date':None})
    fig.savefig(OUT/'feature_vs_nll.png',dpi=180)
    plt.close(fig)

    associations=[]
    for metric,_,_ in features:
        usable=p1.loc[p1.delta.notna()&p1[metric].notna()]
        groups=[('P1_all_available',usable)]+[(f'P1_r{r}',g) for r,g in usable.groupby('r') if len(g)>=3]
        for name,g in groups:
            associations.append(dict(feature=metric,group=name,tasks=len(g),
                pearson=g[metric].corr(g.delta),spearman=g[metric].corr(g.delta,method='spearman'),
                inference='descriptive only; no p-value or independence assumption'))
    pd.DataFrame(associations).to_csv(OUT/'associations.csv',index=False,float_format='%.15g')
    lines=['<!-- Generated by make_structure_feature_summary.py. -->',
        '# Full-data shell and context characteristics beside NLL gaps','',
        '[Definitions and interpretation](README.md) · [All columns](nll_comparison.csv) · [All references](summary.csv) · [Characteristic 1](../comparison.md)','',
        'All frequencies use the entire eligible task and the same full-data center as characteristic 1. Positive Δ favors PL. NLLs are copied from existing prediction results. No new prediction or significance test is run.','',
        '## 2. Same display, same Kendall-distance shell','',
        'TV compares the actual conditional ranking frequencies with a uniform distribution over **all** permutations in that shell, including zero-count permutations. Values are averaged over occupied nontrivial shells, weighted by their observation counts. “Uniform sampling reference” is the exact expected empirical TV at the same shell sizes/counts under iid uniform draws and a fixed reference; it is not a fitted SM prediction, calibrated test, or bias-corrected population estimate.','',
        '| Task / shell summaries | TV | Uniform sampling reference | Difference | Median observations per shell | Median m/a | Observations in repeated shells | Existing Δ |',
        '|---|---:|---:|---:|---:|---:|---:|---:|']
    for row in p1.itertuples():
        per_ranking=f'{row.shell_expected_count_median:.3g}' if np.isfinite(row.shell_expected_count_median) else 'NA'
        lines.append(f'| [{label(row.dataset)}](shells/{row.dataset}.csv) | {number(row.shell_tv)} | '
            f'{number(row.shell_iid_uniform_expected_tv)} | {number(row.shell_excess_tv,signed=True)} | '
            f'{number(row.shell_count_median,decimals=1)} | {per_ranking} | '
            f'{number(row.shell_occurrence_share_count_ge2,100,1)}% | '
            f'{number(row.delta,decimals=5,signed=True)} |'.replace('NA%','NA'))
    lines += ['', 'For r=2, each shell contains one possible order: within-shell uniformity has no nontrivial content, so TV is NA. A one-observation nontrivial shell has TV=1−1/a solely because of its sample size; its observed TV equals the nominal sampling reference.','',
        '## 3. Same pair across exact displayed sets','',
        'C is the occurrence-weighted RMS variation of each pair’s observed win rate across exact displayed sets, centered separately within each pair. γ is the pooled within-pair slope of win rate against displayed-center gap h. The replacement contrast changes **one nonfocal item only**, holds all other displayed items fixed, and reports higher-h minus lower-h win rate for the same pair. Each changed-gap replacement has Δh=1. C is unsigned; positive γ/replacement effects agree with the direction in the SM example, but may arise from sampling or population/display mixtures.','',
        '| Task / pair summaries | C, pp | Pair occurrences in repeated displays | γ, pp per h | One-item replacement effect, pp | Changed-h edges | Edges with both displays repeated | Existing Δ |',
        '|---|---:|---:|---:|---:|---:|---:|---:|']
    for row in p1.itertuples():
        lines.append(f'| [{label(row.dataset)}](pairs/{row.dataset}.csv) | {number(row.context_display_sd,100,2)} | '
            f'{number(row.context_occurrence_share_repeated_display,100,1)}% | '
            f'{number(row.context_gap_slope,100,2,True)} | {number(row.swap_gap_effect,100,2,True)} | '
            f'{row.swap_gap_edges} | {row.swap_gap_edges_both_repeated} | {number(row.delta,decimals=5,signed=True)} |'.replace('NA%','NA'))
    lines += ['', 'Edges reuse observations and are not independent samples. Fixed full displays and r=2 provide no same-pair display contrast; NA does not mean context invariance was verified. The CSV also gives same-h residual variation, counts of eligible pairs, and the replacement effect restricted to edges with both displays observed at least twice. That support summary is supplementary; the primary calculations retain every observation.','',
        '## ATP tasks and incomplete NLL comparisons','',
        'All ten ATP annual tasks have r=2. Their shell and same-pair display characteristics are structurally unavailable; each is still joined to the existing T1 seen-player target. Its full-year feature population and regularized fitting procedure differ from P1.','',
        '| ATP task | Shell characteristic | Context characteristic | Existing T1 Δ |',
        '|---|---|---|---:|']
    for row in data.loc[data.nll_study.eq('T1')].itertuples():
        lines.append(f'| {label(row.dataset)} | NA: singleton shells | NA: pair fixes display | {row.delta:+.5f} |')
    lines += ['', 'The four incomplete P1 means remain NA in every table and plot. Conditional means below use only the listed successful comparisons and are not substituted for complete Δ.','',
        '| Task | Finite repetitions | Conditional Δ |','|---|---:|---:|']
    for row in p1.loc[p1.delta.isna()].itertuples():
        lines.append(f'| {label(row.dataset)} | {row.paired_repetitions}/{row.planned_repetitions} | {row.conditional_delta:+.5f} |')
    lines += ['', '## Visual comparison','',
        '![Full-data structural characteristics and recorded NLL gaps](feature_vs_nll.svg)','',
        'Only available features with complete P1 NLL means are plotted. The first panel subtracts the nominal sampling reference to display the scale; it does not remove center uncertainty, report dependence, or mixtures. Features, report lengths and sampling support differ across tasks. [Associations](associations.csv) are descriptive, with no p-values or population claims.','']
    return '\n'.join(lines)


def run():
    """Compatibility entry point for the unified three-characteristic report."""
    from make_feature_summary import run as unified_run
    unified_run()


if __name__=='__main__':
    run()
