"""Render full-data descriptive features beside already recorded NLL gaps."""
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

from describe_pair_features import OUT


NAMES = {'beans':'Beans','sushi_a':'Sushi A','sushi_b':'Sushi B','wheat':'Wheat',
         'sounds':'Sounds','patras_cost':'PatrasIQ cost','patras_population':'PatrasIQ population'}
NAMES.update({f'00024-0000000{i}':f'Dots 2013, gap {h}' for i,h in enumerate([3,5,7,9],1)})
NAMES.update({f'00025-0000000{i}':f'Puzzle, minimum {h} steps' for i,h in enumerate([11,5,7,9],1)})


def label(name):
    return NAMES.get(name, name.replace('dots2024_','Dots 2024 ').replace('atp_','ATP ').replace('_',' '))


def render_section():
    frame = pd.read_csv(OUT/'nll_comparison.csv')
    p1 = frame.loc[frame.nll_study.eq('P1') & frame.delta.notna()]
    rows=[]
    groups=[('P1_all_complete',p1)] + [(f'P1_r{r}',g) for r,g in p1.groupby('r') if len(g)>=3]
    groups += [('T1_ATP_seasons',frame.loc[frame.nll_study.eq('T1')])]
    for name,g in groups:
        rows.append(dict(group=name,tasks=len(g),
            pearson=float(g.heterogeneity_sd.corr(g.delta)),
            spearman=float(g.heterogeneity_sd.corr(g.delta,method='spearman')),
            inference='descriptive association only; no independent-task assumption or p-value'))
    association=pd.DataFrame(rows)
    association.to_csv(OUT/'associations.csv',index=False,float_format='%.15g')

    plt.rcParams.update({'font.family':'DejaVu Sans','font.size':10,'svg.hashsalt':'equal-h-data-features'})
    fig,axes=plt.subplots(1,2,figsize=(13,5.5),gridspec_kw={'width_ratios':[1.8,1]},layout='constrained')
    colors={2:'#277da8',3:'#a24a38',4:'#427b45',5:'#a16b13',6:'#784e9f',10:'#1d8280'}
    ax=axes[0]
    for r,g in p1.groupby('r'):
        ax.scatter(100*g.heterogeneity_sd,g.delta,c=colors[int(r)],s=48,label=f'r = {int(r)}',zorder=3)
    for row in p1.itertuples():
        if row.dataset in ['sushi_a','patras_cost','wheat','sounds','dots2024_A_r3','dots2024_B_r6','00025-00000002']:
            offsets={'sushi_a':(4,5),'patras_cost':(4,5),'wheat':(4,-15),
                     'sounds':(4,-13),'dots2024_A_r3':(-83,7),
                     'dots2024_B_r6':(-100,-14),'00025-00000002':(4,-13)}
            ax.annotate(label(row.dataset),(100*row.heterogeneity_sd,row.delta),
                        xytext=offsets[row.dataset],textcoords='offset points',fontsize=8)
    ax.set_title('P1: 19 tasks with all 30 NLL comparisons')
    ax.set_ylabel('Recorded whole-ranking NLL(SM) - NLL(PL)\nPositive favors PL')
    ax.set_xlim(-1,36);ax.set_ylim(-.09,.32)
    ax.legend(ncols=3,loc='upper left',frameon=False,fontsize=8)
    atp=frame.loc[frame.nll_study.eq('T1')]
    axes[1].scatter(100*atp.heterogeneity_sd,atp.delta,c='#526877',s=42)
    for row in atp.itertuples():
        axes[1].annotate(row.dataset[-4:],(100*row.heterogeneity_sd,row.delta),
                         xytext=(3,4),textcoords='offset points',fontsize=8)
    axes[1].set_title('ATP: 10 chronological season comparisons')
    axes[1].set_ylim(-.005,.05)
    for a in axes:
        a.axhline(0,color='#858585',lw=.8,zorder=1)
        a.set_xlabel('Full-data equal-h heterogeneity H (percentage points)')
        a.spines[['top','right']].set_visible(False)
        a.grid(axis='y',alpha=.18)
    fig.suptitle('Observed pair-frequency heterogeneity and existing predictive gaps',fontsize=14)
    fig.savefig(OUT/'feature_vs_nll.svg',metadata={'Date':None})
    fig.savefig(OUT/'feature_vs_nll.png',dpi=180)
    plt.close(fig)

    table=['<!-- Generated by make_pair_feature_summary.py; edit methods in README.md. -->',
        '# Full-data features beside recorded prediction gaps','',
        '[Definitions, interpretation and limitations](README.md) · [CSV](nll_comparison.csv) · [Every h](by_gap.csv)','',
        'H and H1 are **percentage points**, calculated from the entire task. H compares pairs only within the same h before aggregating; H1 restricts that comparison to adjacent pairs. Median count is the number of reports per observed pair × h cell. Δ is the saved SM-minus-PL whole-ranking NLL gap in nats/report. Counts and empirical frequencies are not estimates with a universal binomial CI.','',
        '## P1 datasets','',
        'The reference centers for all 23 tasks are certified full-data Kendall-objective minima. Original prediction fits and test losses are unchanged. Four incomplete means remain unavailable; conditional means use only the listed successful repetitions.','',
        '| Task / exact pair counts | H | H1 | Median count | Occurrences in cells with ≥5 reports | Δ | Finite repetitions | Conditional Δ if incomplete |',
        '|---|---:|---:|---:|---:|---:|---:|---:|']
    def table_row(row,temporal=False):
        delta=f'{row.delta:+.5f}' if np.isfinite(row.delta) else 'Unavailable'
        conditional=f'{row.conditional_delta:+.5f}' if np.isfinite(row.conditional_delta) else '—'
        return (f'| [{label(row.dataset)}](pairs/{row.dataset}.csv) | {100*row.heterogeneity_sd:.2f} | '
            f'{100*row.h1_heterogeneity_sd:.2f} | {row.count_median:g} | '
            f'{100*row.occurrence_share_count_ge5:.1f}% | {delta} | '
            f'{row.paired_repetitions}/{row.planned_repetitions} | {conditional} |')
    table.extend(table_row(row) for row in frame.loc[frame.nll_study.eq('P1')].itertuples())
    table += ['', '## ATP yearly tasks','',
        'Each feature uses all completed, prior-catalogue-eligible matches in that year, including both halves and test matches whose players were unseen in training. Centers are approximate. Δ uses the existing T1 main seen-player July–December target: bounded/shrunk efficient-center SM versus ridge PL. Thus the feature population is broader than this prediction target; these values are not pooled with P1.','',
        '| Task / exact pair counts | H | H1 | Median count | Occurrences in cells with ≥5 reports | Δ | Seasonal comparisons | Conditional Δ |',
        '|---|---:|---:|---:|---:|---:|---:|---:|']
    table.extend(table_row(row,True) for row in atp.itertuples())
    table += ['', '## Descriptive associations','',
        'These are correlations of dataset-level points, not additional experiments, significance tests, model-selection rules, or independent replication counts. Shared respondents/conditions, different r and cell support confound the pooled relationship. Incomplete P1 means are excluded; no conditional substitute is used. Only within-r groups with at least three complete tasks are listed.','',
        '| Points | Tasks | Pearson | Spearman |','|---|---:|---:|---:|']
    table.extend(f'| {row.group} | {row.tasks} | {row.pearson:+.3f} | {row.spearman:+.3f} |' for row in association.itertuples())
    table += ['', '![Equal-h data features versus recorded NLL differences](feature_vs_nll.svg)','',
        'Axes differ between P1 and ATP. Every plotted point is a descriptive feature paired with an existing loss gap; no new confidence interval is computed.','']
    return '\n'.join(table)


def run():
    """Compatibility entry point for the unified three-characteristic report."""
    from make_feature_summary import run as unified_run
    unified_run()


if __name__=='__main__':
    run()
