"""Present all three saved data characteristics in one report; no fitting."""
import json
import re

import numpy as np
import pandas as pd

from describe_pair_features import ROOT, OUT, digest
from make_pair_feature_summary import label, render_section as render_pairs
from make_structure_feature_summary import number, render_section as render_structure


def section(text, heading, end=None):
    body = text.split('## '+heading+'\n\n', 1)[1]
    return body.split('## '+end+'\n\n', 1)[0].strip() if end else body.strip()


def structure_links(text):
    return re.sub(r'\]\((?!https?://|#)([^)]+)\)',
                  lambda m: ']('+str('structure/'+m.group(1))+')', text)


def run():
    pair = pd.read_csv(OUT/'nll_comparison.csv').set_index('dataset')
    structural = pd.read_csv(OUT/'structure/nll_comparison.csv').set_index('dataset')
    common = sorted(set(pair.columns) & set(structural.columns))
    pd.testing.assert_frame_equal(pair[common].sort_index(), structural[common].sort_index())
    combined = pair.join(structural.drop(columns=common), how='left', validate='one_to_one').reset_index()
    assert len(combined) == 33 and combined.dataset.nunique() == 33
    combined.to_csv(OUT/'all_features.csv', index=False, float_format='%.15g')

    pair_text, structure_text = render_pairs(), render_structure()
    lines = [
        '<!-- Generated by make_feature_summary.py from saved feature tables; no refitting. -->',
        '# All three data characteristics beside prediction gaps', '',
        '[Definitions and formulas](README.md) · [All features in one CSV](all_features.csv) · '
        '[Detailed pair counts](pairs/) · [Shell summaries](structure/shells/) · [Context summaries](structure/pairs/)', '',
        'Every feature uses the entire eligible task and the same full-data reference order. '
        'Δ = NLL(SM) − NLL(PL) is copied from the existing predictive comparison; positive favors PL. '
        'No new prediction experiment, split, confidence interval or significance test is introduced.', '',
        '| Characteristic | Overview columns | Reading the value |',
        '|---|---|---|',
        '| 1. Different pairs at equal h | H, percentage points | Observed cross-pair dispersion, compared within each exact displayed-center gap before aggregation |',
        '| 2. Same display and Kendall shell | TV / uniform reference | Empirical nonuniformity / its nominal iid-uniform sampling scale at the actual shell counts; the reference is not a calibrated test |',
        '| 3. Same pair across displays | C and R, percentage points | C: unsigned variation across exact displays. R: higher-h minus lower-h rate when exactly one other item is replaced |', '',
        'Read these values with the support tables below: one-observation cells can generate large H, TV or C. '
        'NA denotes an undefined contrast or incomplete predictive comparison, not verified equality.', '',
        '## All three characteristics by dataset', '',
        '### P1 tasks', '',
        'All 23 tasks have certified full-data reference centers. The existing NLL means use 30 confirmation partitions; '
        'four incomplete paired means remain NA. Finite-only conditional means are listed separately in the detail table.', '',
        '| Task | r | 1: H, pp | 2: TV / uniform reference | 3: C, pp | 3: R, pp | Existing Δ | Finite partitions |',
        '|---|---:|---:|---:|---:|---:|---:|---:|']

    def overview(row):
        shell = (number(row.shell_tv, decimals=5)+' / '+number(row.shell_iid_uniform_expected_tv, decimals=5)
                 if np.isfinite(row.shell_tv) else 'NA')
        return (f'| {label(row.dataset)} | {row.r} | {number(row.heterogeneity_sd,100,2)} | {shell} | '
                f'{number(row.context_display_sd,100,2)} | {number(row.swap_gap_effect,100,2,True)} | '
                f'{number(row.delta,decimals=5,signed=True)} | {row.paired_repetitions}/{row.planned_repetitions} |')

    lines.extend(overview(row) for row in combined.loc[combined.nll_study.eq('P1')].itertuples())
    lines += ['', '### ATP annual tasks', '',
        'These ten tasks have r=2, so characteristics 2 and 3 have no nontrivial contrast. '
        'Their approximate-center, full-year features and regularized T1 seen-player July–December prediction target '
        'are kept separate from P1. Each NLL gap is one seasonal comparison.', '',
        '| Task | r | 1: H, pp | 2: TV / uniform reference | 3: C, pp | 3: R, pp | Existing Δ | Seasonal comparisons |',
        '|---|---:|---:|---:|---:|---:|---:|---:|']
    lines.extend(overview(row) for row in combined.loc[combined.nll_study.eq('T1')].itertuples())
    lines += ['', '## Reading the three characteristics together', '',
        '- Sushi A has H=7.36 points, but its shell TV .99351 is close to the nominal sampling reference .99335; '
        'its fixed display makes characteristic 3 unavailable. Its existing Δ=+.02555 favors PL.',
        '- Beans has shell TV .23473 versus reference .24580 and R=+2.66 points with repeated observations in both '
        'displays of all 420 matched contrasts. Its Δ=+.01251 favors PL despite the positive h association.',
        '- Dots 2013 and Puzzle combine relatively small H with complete NLL gaps favoring SM. Their coded displays '
        'are fixed, so they cannot establish a same-pair display effect. Nonzero shell-frequency departures do not '
        'by themselves establish that PL predicts better.',
        '- Wheat and dots2024 need particular care about sparse cells. Wheat has R=+7.56 points, but only 70 of '
        '2,022 contrasts have both displays observed at least twice. For dots2024 B r=6, R is negative while the '
        'broader within-pair slope is positive; these use different contrasts and do not contradict one another.', '',
        'The three characteristics describe different constraints. They are not votes to tally for a model winner. '
        'Reference-center estimation, observation counts, assessor/display mixtures and ranking length affect '
        'interpretation; the existing whole-ranking NLL remains the predictive comparison.', '',
        '## 1. Equal-gap pair frequencies', '',
        'H and H1 are percentage points. H1 restricts the comparison to adjacent pairs. Median count is per observed '
        'pair × h cell. The ≥5 field describes support and does not filter the feature calculation.', '',
        section(pair_text, 'P1 datasets', 'ATP yearly tasks'), '',
        '### ATP pair-frequency support', '',
        section(pair_text, 'ATP yearly tasks', 'Descriptive associations'), '',
        '## 2. Same display, same Kendall-distance shell', '',
        structure_links(section(structure_text, '2. Same display, same Kendall-distance shell',
                                '3. Same pair across exact displayed sets')), '',
        '## 3. Same pair across exact displayed sets', '',
        structure_links(section(structure_text, '3. Same pair across exact displayed sets',
                                'ATP tasks and incomplete NLL comparisons')), '',
        '## Visual comparisons and descriptive associations', '',
        section(pair_text, 'Descriptive associations'), '',
        structure_links(section(structure_text, 'Visual comparison')), '']
    (OUT/'comparison.md').write_text('\n'.join(lines))
    (OUT/'structure/comparison.md').write_text(
        '# Data-characteristic comparison\n\n'
        'All three characteristics now appear in the [single dataset comparison](../comparison.md), '
        'with a joint overview, support tables and figures.\n\n'
        '## 2. Same display, same Kendall-distance shell\n\n'
        '[Read this section in the combined comparison](../comparison.md#2-same-display-same-kendall-distance-shell).\n\n'
        '## 3. Same pair across exact displayed sets\n\n'
        '[Read this section in the combined comparison](../comparison.md#3-same-pair-across-exact-displayed-sets).\n')

    manifest = json.loads((OUT/'manifest.json').read_text())
    for name in ['make_feature_summary.py', 'make_pair_feature_summary.py', 'make_structure_feature_summary.py']:
        manifest['code_sha256'][name] = digest(ROOT/name)
    for name in ['comparison.md', 'all_features.csv', 'associations.csv', 'feature_vs_nll.svg', 'feature_vs_nll.png']:
        manifest['output_sha256'][name] = digest(OUT/name)
    (OUT/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
    structural_manifest = json.loads((OUT/'structure/manifest.json').read_text())
    structural_manifest['inputs']['data/features/manifest.json'] = digest(OUT/'manifest.json')
    for name in ['make_structure_feature_summary.py', 'make_feature_summary.py']:
        structural_manifest['code_sha256'][name] = digest(ROOT/name)
    for name in ['comparison.md', 'associations.csv', 'feature_vs_nll.svg', 'feature_vs_nll.png']:
        structural_manifest['output_sha256'][name] = digest(OUT/'structure'/name)
    (OUT/'structure/manifest.json').write_text(json.dumps(structural_manifest,indent=2)+'\n')
    print('Rendered all three saved characteristics for 33 tasks; prediction and feature source tables unchanged.')


if __name__ == '__main__':
    run()
